### ISSUE TITLE
Crash when placing fast engine next to Buildcraft Quarry

### ISSUE THREAD

**Issue by KobraKid** [Chocohead/EU-MJ-Engine#8]
Upon placing a fast engine next to a buildcraft quarry, minecraft crashes. The following is (the important parts of) my crash report. I can provide the whole crash report file too.

Time: 3/30/19 2:36 PM
Description: Unexpected error

java.lang.AbstractMethodError: Method com/chocohead/eumj/te/Engine_TEs.getPlaceHandler()Lic2/core/ref/TeBlock$ITePlaceHandler; is abstract
	at com.chocohead.eumj.te.Engine_TEs.getPlaceHandler(Engine_TEs.java)
	at ic2.core.block.BlockTileEntity.canReplace(BlockTileEntity.java:406)
	at ic2.core.item.block.ItemBlockTileEntity.placeBlockAt(ItemBlockTileEntity.java:64)
	at net.minecraft.item.ItemBlock.func_180614_a(ItemBlock.java:54)
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:187)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:477)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1579)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1808)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.chocohead.eumj.te.Engine_TEs.getPlaceHandler(Engine_TEs.java)
	at ic2.core.block.BlockTileEntity.canReplace(BlockTileEntity.java:406)
	at ic2.core.item.block.ItemBlockTileEntity.placeBlockAt(ItemBlockTileEntity.java:64)
	at net.minecraft.item.ItemBlock.func_180614_a(ItemBlock.java:54)
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:187)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:477)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1579)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['01111110'/131, l='MpServer', x=299.25, y=64.00, z=-332.18]]
	Chunk stats: MultiplayerChunkCache: 306, 306
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (81,64,-81), Chunk: (at 1,4,15 in 5,-6; contains blocks 80,0,-96 to 95,255,-81), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 891173 game time, 1226274 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 11 total; [EntityCreeper['Creeper'/121352, l='MpServer', x=301.55, y=47.00, z=-348.75], EntitySquid['Squid'/122413, l='MpServer', x=345.47, y=61.81, z=-320.40], EntityItemFrame['entity.ItemFrame.name'/108668, l='MpServer', x=291.03, y=63.50, z=-345.50], EntityPlayerSP['01111110'/131, l='MpServer', x=299.25, y=64.00, z=-332.18], EntitySkeleton['Skeleton'/113801, l='MpServer', x=305.46, y=68.00, z=-346.39], EntityItemFrame['entity.ItemFrame.name'/107669, l='MpServer', x=291.03, y=64.50, z=-345.50], EntityRabbit['Rabbit'/107689, l='MpServer', x=241.52, y=70.00, z=-277.74], EntityLlama['Llama'/107693, l='MpServer', x=287.47, y=82.00, z=-400.09], EntityAncientGolem['Ancient Golem'/107706, l='MpServer', x=304.92, y=36.00, z=-367.30], EntityChicken['Chicken'/107710, l='MpServer', x=290.50, y=86.00, z=-409.16], EntitySkeleton['Skeleton'/122579, l='MpServer', x=371.50, y=39.00, z=-334.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Chocohead** [comment]
The mod version list at the bottom of the crash would be quite helpful, but going off what is there I'd say you need to update IC2.

**Comment by KobraKid** [comment]
Thank you, upgrading to latest IC2 resolved the issue.

**Comment by Chocohead** [comment]
Good to hear you got it working.
